import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Aurora from "@/components/reactbits/Aurora";
import Navbar from "@/components/navbar/Navbar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1, minimum-scale=1"
                />
            </head>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen w-full relative`}
            >
                <Navbar />
                <div className="absolute inset-0 top-0 z-[-1] min-h-screen">
                    <Aurora
                        colorStops={["#062b75", "#38b072", "#80b038"]}
                        blend={0.5}
                        amplitude={0.5}
                        speed={0.8}
                    />
                </div>
                {children}
            </body>
        </html>
    );
}
